/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'hideoku' at '15/11/17 22:35' with Gradle 2.7
 *
 * @author hideoku, @date 15/11/17 22:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
